"""empty message

Revision ID: b845cff47043
Revises: a15094813303
Create Date: 2017-04-30 22:17:17.497598

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b845cff47043'
down_revision = 'a15094813303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('head', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'head')
    # ### end Alembic commands ###
